[package]
name = "nvgx-ogl"
version = "0.1.0"
edition = "2024"

[features]
default = ["wirelines"]
wirelines = ["nvgx/wirelines"]


[dependencies]
nvgx = { path = "../" }
slab = "0.4.2"
anyhow = "1.0.26"
gl = { version = "0.14.0" }
bytemuck = "1.23.0"